name: Sync and Deploy to Vercel

on:
  push:
    branches:
      - feat/deploy-preview

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        persist-credentials: false 
        fetch-depth: 0 

    - name: Remove default git credentials
      run: |
        git config --global --unset credential.helper || true
        rm -f ~/.git-credentials

    - name: Set up Git user
      run: |
        git config --global user.name "Hello"  
        git config --global user.email "test@example.com"  

    - name: Configure Git to use Personal Access Token
      run: |
        echo "https://x-access-token:${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com" > ~/.git-credentials
        git config --global credential.helper store

    - name: Push to Personal Repo
      run: |
        git remote add personal https://github.com/korawit-alt/sucu-frontend-preview.git
        git push personal HEAD:dev --force

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod --confirm'  
        working-directory: '.'  